### This is the main way to configure the application (other than annotations).

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

server:
  port: 8080

forex.service:
    exchangeDateFormat: yyyy-MM-dd
    expiryDateForCurrencyInSeconds: 60
    supportedCurrencies: EUR,USD,INR,AUD,BGN,BRL,CAD,CHF,CNY,CZK,DKK,GBP,JPY,MYR,NZD # TODO Need to move this to a config table instead and make it enumerated
    clients:
      fixer:
           url: http://api.fixer.io/


#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: forex-service
  version: 0.1
  description: Forex Service supporting multi-currency
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

hotel.service:
  name: 'default profile:'
---
spring:
  profiles: test
  h2:
    console:
      enabled: true

spring.jpa:
    hibernate.ddl-auto: create-drop

hotel.service:
  name: 'test profile:'

logging:
  file: boot_forex_service.log
  org.hibernate: INFO

